// Generated by RPG Maker.
// Do not edit this file directly.
var $plugins =
[
{"name":"DynamicResize","status":true,"description":"在浏览器中自动适配游戏窗口尺寸","parameters":{"Base Width":"960","Base Height":"720","Maintain Aspect Ratio":"true","Resize Delay":"100"}}
];
